### ISSUE TITLE
Check list for Drivers

### ISSUE THREAD

**Issue by baileypf** [The-Charge/2015_TrashBot#7]
A list detailing for the drivers with the important things from a programming aspect that need to be there at the beginning of a match

**Comment by Shalmezad** [comment]
See #21 
Make sure that the lift is at the very bottom before the robot is turned on.

**Comment by Shalmezad** [comment]
Didn't see this in the list of issues.

In addition to the checklist, a diagram needs to be made showing the starting position of all autonomous' so that they can be set up properly.

Also, a diagram needs to be made for each autonomous showing not just where they start, but where they go. This is helpful for coordinating autonomous strategy with other teams.
